# Generated by Django 4.1.2 on 2022-10-27 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nps", "0003_alter_company_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="persons",
        ),
        migrations.AlterField(
            model_name="nps",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyuser",
            unique_together={("company", "user")},
        ),
    ]
