# Generated by Django 4.1.2 on 2022-10-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nps", "0004_remove_company_persons_alter_nps_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nps",
            name="user",
        ),
        migrations.AddField(
            model_name="nps",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nps.companyuser",
            ),
        ),
    ]
