# Generated by Django 4.1.2 on 2022-10-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nps", "0005_remove_nps_user_nps_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="nps",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
